### PR TITLE
Fix default app redirect issue.

### PR DESCRIPTION
**Pull request by jbouder**
## What does this implement/fix?

_Put a `x` in the boxes that apply_

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [x] Did you test the pull request locally?
- [ ] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [ ] This content adheres to the Nebari style guides.

#### Non-text content

- [ ] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

### CODE REVIEW

**Comment by viniciusdc** [comment]
@jbouder uhm.. I am still encountering the issue, though now it's more stable, and I don't see any blank pages, but the direct profile creation still happens. While in admin, I also glanced at the admin page and attempted to check the Spawn page from there as well, but it automatically spun the instance...
image

I have a feeling something amiss is going on with the `/hub/spawn` route, since that is supposed to look like this:
image

**Comment by viniciusdc** [comment]
I am also seeing this in the logs: 
```
INFO:     127.0.0.1:0 - "GET /services/japps/user HTTP/1.1" 200 OK
[D 2024-12-11 12:15:58.545 JupyterHub scopes:1010] Checking access to /hub/spawn/admin via scope servers!server=admin/
[D 2024-12-11 12:15:58.545 JupyterHub pages:216] Triggering spawn with default options for admin
[D 2024-12-11 12:15:58.545 JupyterHub base:1095] Initiating spawn for admin
[D 2024-12-11 12:15:58.545 JupyterHub base:1099] 0/100 concurrent spawns
[D 2024-12-11 12:15:58.545 JupyterHub base:1104] 0 active servers
```

**Comment by jbouder** [comment]
Yeah, I think this fixes the UI bug...however I'm not sure how to get JupyterHub to load the server options page. Based on the logs you provided, I wonder if the admin account is missing some scope.

**Comment by viniciusdc** [comment]
> Yeah, I think this fixes the UI bug...however I'm not sure how to get JupyterHub to load the server options page. Based on the logs you provided, I wonder if the admin account is missing some scope.

Ineed, I think I am running this wrong, the profiles list targets the `KubeSpawne` object, which should only be available on a K8s environment. I will test this on a local nebari since this might be why I am not getting the profiles to show up

**Comment by viniciusdc** [comment]
Working! 
Peek 11-12-2024 12-35
I will just do another pass, to make sure its not a false positive. If all works this will be ready to go

**Review by viniciusdc — APPROVED** [review]
LGTM! Thanks @jbouder

**Pull request merged**
