### PR TITLE
Send server owner

### PR DESCRIPTION
**Pull request by kildre**
Adds the owner of the app to the POST request when starting an app
## Reference Issues or PRs

https://github.com/nebari-dev/jhub-apps/issues/529

[This fixes the issue of a missing owner in the request.](https://gitlab.jatic.net/jatic/team-metrostar/t-e-platform/-/issues/858)
## What does this implement/fix?
Adds the owner's name to the request when starting an app
_Put a `x` in the boxes that apply_

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds a feature)
- [ ] Breaking change (fix or feature that would cause existing features not to work as expected)
- [ ] Documentation Update
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build related changes
- [ ] Other (please describe):

## Testing

- [X] Did you test the pull request locally?
- [X] Did you add new tests?

#### Text styling

- [ ] The content is written with [plain language](https://www.plainlanguage.gov/guidelines/) (where relevant).
- [ ] If there are headers, they use the proper header tags (with only one level-one header: `H1` or `#` in markdown).
- [ ] All links describe where they link to (for example, check the [Nebari website](https://nebari.dev/)).
- [X] This content adheres to the Nebari style guides.

#### Non-text content

- [X] All content is represented as text (for example, images need alt text, and videos need captions or descriptive transcripts).
- [ ] If there are emojis, there are not more than three in a row.
- [ ] Don't use [flashing GIFs or videos](https://www.w3.org/TR/UNDERSTANDING-WCAG20/seizure-does-not-violate.html).
- [ ] If the content were to be read as plain text, it still makes sense, and no information is missing.

## Any other comments?
image

### CODE REVIEW

**Comment by kildre** [comment]
@aktech @jbouder please rewview PR

**Review by jbouder — APPROVED** [review]
Looks good and works as far as I can tell.

**Comment by aktech** [comment]
Looks like the `owner` is empty on a server I tried to start:

Screenshot 2024-11-18 at 10 55 53 pm

**Comment by jbouder** [comment]
> @aktech so the issue was my oversight in that I only provide logic for clicking on the Menu Item 'Start' I didn't provide the logic for just clicking on the card and the clicking Start in the modal. Fixed this, it should be working either way you start an app and the name of the creator will be sent in the request. Please review again.

That explains why I didn't run into any issues. I initiated a start from the context menu.

**Comment by aktech** [comment]
Also I noticed, when you try opening a shared app which is stopped by directly going to the URL, previously it would show you a pop up asking if you want to start the app (@jbouder implemented this in past), now it returns 404 and is stuck on loading infinitely.

https://github.com/user-attachments/assets/8cfb0361-6919-4c24-a955-c9560ca49962

I am not sure, if this is due to this PR or a bug prior to this, most likely latter?

**Comment by jbouder** [comment]
> Also I noticed, when you try opening a shared app which is stopped by directly going to the URL, previously it would show you a pop up asking if you want to start the app (@jbouder implemented this in past), now it returns 404 and is stuck on loading infinitely.
> 
>  Screen.Recording.2024-11-20.at.7.00.01.pm.mov 
> I am not sure, if this is due to this PR or a bug prior to this, most likely latter?

I just did a few tests (on main) of directly navigating to a stopped app, and here is what I'm seeing:
- My App: Redirected home and modal came up
- Non-shared App: Default 404 page
- Shared App: infinite loop

I'm guessing this is an existing bug, which could have just been a use case we didn't test.

**Comment by aktech** [comment]
Ah, I see. Thanks for confirming. I have created a separate issue for the same: https://github.com/nebari-dev/jhub-apps/issues/534

**Review by aktech — APPROVED** [review]
Looks good to me, thanks for fixing this 🎉

**Pull request merged**
